site_name: Focoos AI SDK

site_url: https://focoosai.github.io/focoos/
repo_url: https://github.com/FocoosAI/focoos
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    - scheme: slate
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - assets/stylesheets/custom.css
  - https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&family=DM+Mono&display=swap # Load Google Fonts (DM Sans Regular, Medium, and DM Mono)

plugins:
  - search
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  - include-markdown

nav:
  - Focoos AI:
      - Welcome: index.md
      - Installation: setup.md
      - Models: models.md

  - Examples:
      - Cloud Inference: examples/cloud_inference.md
      - Local Inference: examples/local_inference.md
      - Cloud Training: examples/cloud_training.md
      - Manage Datasets: examples/datasets.md
      - Manage Models: examples/dashboard.md
      - User Details: examples/user.md
      - Gradio: examples/gradio.md
      - Model Metrics: examples/model_metrics.md
  - Focoos Models:
      - Overview: models.md
      - Semantic segmentation:
        - fai-m2f-l-ade: models/fai-m2f-l-ade.md
        - fai-m2f-m-ade: models/fai-m2f-m-ade.md
        - fai-m2f-s-ade: models/fai-m2f-s-ade.md
      - Object detection:
        - fai-rtdetr-l-coco: models/fai-rtdetr-l-coco.md
        - fai-rtdetr-m-coco: models/fai-rtdetr-m-coco.md
        - fai-rtdetr-s-coco: models/fai-rtdetr-s-coco.md
        - fai-rtdetr-n-coco: models/fai-rtdetr-n-coco.md
        - fai-rtdetr-m-obj365: models/fai-rtdetr-m-obj365.md
      - Instance_segmentation:
        - fai-m2f-l-coco-ins: models/fai-m2f-l-coco-ins.md
  - API Reference:
      - focoos: api/focoos.md
      - remote model: api/remote_model.md
      - local model: api/local_model.md
      - remote dataset: api/remote_dataset.md
      - runtime: api/runtime.md
      - ports: api/ports.md
  - Development:
      - Contributing: development/contributing.md
      - Code of Conduct: development/code_of_conduct.md
      - Changelog: development/changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: "#"
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-RP4PM5PGLN
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FocoosAI/focoos
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/focoosai

copyright: Copyright &copy; 2024 FocoosAI

watch:
  - focoos
