name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get next version without tagging
        id: get_next_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      # Step 2: Aggiornare pyproject.toml con la nuova versione
      - name: Update pyproject.toml with new version
        run: |
          sed -i 's/version = ".*"/version = "${{ steps.get_next_version.outputs.new_version }}"/' pyproject.toml

      # Step 3: Fare commit della modifica
      - name: Commit updated pyproject.toml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[bot]: update version to ${{ steps.get_next_version.outputs.new_version }}"
          file_pattern: pyproject.toml
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          custom_tag: ${{ steps.get_next_version.outputs.new_tag }}
          tag_prefix: ""
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_next_version.outputs.new_tag }}
          name: Release ${{ steps.get_next_version.outputs.new_tag }}
          body: ${{ steps.get_next_version.outputs.changelog }}
          generateReleaseNotes: true

  mkdocs:
    runs-on: ubuntu-22.04
    needs: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version:  3.12
      - name: Install the latest version of uv and set the python version to 3.12
        uses: astral-sh/setup-uv@v4
        with:
          python-version:  3.12
      - name: Install dependencies
        run: uv pip install .[docs]
      - name: Build mkdocs site
        run: mkdocs build --clean
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
