name: Run Focoos tests
on:
  pull_request:
  workflow_dispatch:
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  Run-test:

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8","3.9", "3.10", "3.11","3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: install make
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install ffmpeg libsm6 libxext6 make  -y
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version:  ${{ matrix.python-version }}
      - name: 🐍 Setup Python and uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version:  ${{ matrix.python-version }}
      - name: 📦 Install dependencies
        run: uv pip install .[cpu,dev]
      - name: 🧪 Run test
        run: make test
      - name: Pytest coverage comment
        if: ${{ github.ref_name != 'main' }}
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./tests/coverage.xml
          junitxml-path: ./tests/junit.xml
          report-only-changed-files: true
